/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 /Users/suki/Desktop/head.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model({ color, children, ...props }) {
  const { nodes, materials } = useGLTF("/head.glb");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}>
        <meshStandardMaterial color={color} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Icosphere.geometry}
        position={[-1.04, 0, 0]}
        scale={-0.37}
      >
        <meshStandardMaterial color={color} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
        position={[-0.35, 0.16, -0.97]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={-0.15}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material.002"]}
        position={[0, -0.29, -0.97]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.17}
      />

      {children}
    </group>
  );
}

useGLTF.preload("/head.glb");
