/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 /Users/suki/Desktop/head.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model({ color, children, ...props }) {
  const { nodes, materials } = useGLTF("/head.glb");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}>
        <meshStandardMaterial color={color} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Sphere.geometry}
        position={[1, 0, -0.1]}
        scale={-0.3}
      >
        <meshStandardMaterial color={color} toneMapped={false} />
      </mesh>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
        position={[-0.35, 0.16, -0.964]}
        rotation={[Math.PI / 2, 0, -0.17]}
        scale={-0.15}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material.002"]}
        position={[0, -0.23, -0.97]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
      />

      {children}
    </group>
  );
}

useGLTF.preload("/head.glb");
